stages:          
  - deploy

deploy-job:      # This job runs in the deploy stage.
  stage: deploy
  script:
    - npm install
    #- npm install node@16.13.1
    #- npm --version
    - node -v
    - npm run build
    - ls -ltr
    - cd build
    - pm2 serve build 3000 --spa 
  only: ['main']
