stages:          
  - deploy

deploy-job:      # This job runs in the deploy stage.
  stage: deploy
  script:
    - nvm install 16.0.0
    - npm --version
    - npm run build
    - ls -ltr
    - cd build
    - pm2 serve build 3000 --spa 
  only: ['main']
